// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhAVrHHLztarUkptGpj9nPb815cR0-z9g',
    appId: '1:101004104688:web:1c440216087e7b781dc335',
    messagingSenderId: '101004104688',
    projectId: 'nakoda-7ce2f',
    authDomain: 'nakoda-7ce2f.firebaseapp.com',
    storageBucket: 'nakoda-7ce2f.appspot.com',
    measurementId: 'G-DYGXCNJHZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQChdUFdFYu10KT-vCJVDHah1lZ9QQTYE',
    appId: '1:101004104688:android:d9443594e7949b7e1dc335',
    messagingSenderId: '101004104688',
    projectId: 'nakoda-7ce2f',
    storageBucket: 'nakoda-7ce2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdRjykohxrr9vdjRVwm24Jf7ZPdgt2LEg',
    appId: '1:101004104688:ios:6b7d4a182d49a71a1dc335',
    messagingSenderId: '101004104688',
    projectId: 'nakoda-7ce2f',
    storageBucket: 'nakoda-7ce2f.appspot.com',
    androidClientId: '101004104688-ip377o9ruqc4fto2mu0ahujocptu6eho.apps.googleusercontent.com',
    iosClientId: '101004104688-32s461e1agk5902ecg4vf53lj3nrm2fb.apps.googleusercontent.com',
    iosBundleId: 'com.nakoda.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdRjykohxrr9vdjRVwm24Jf7ZPdgt2LEg',
    appId: '1:101004104688:ios:6b7d4a182d49a71a1dc335',
    messagingSenderId: '101004104688',
    projectId: 'nakoda-7ce2f',
    storageBucket: 'nakoda-7ce2f.appspot.com',
    androidClientId: '101004104688-ip377o9ruqc4fto2mu0ahujocptu6eho.apps.googleusercontent.com',
    iosClientId: '101004104688-32s461e1agk5902ecg4vf53lj3nrm2fb.apps.googleusercontent.com',
    iosBundleId: 'com.nakoda.customer',
  );
}
